### ISSUE TITLE
Compilation error `Package DATABASE does not exist` when trying to compile via `quickload`

### ISSUE THREAD

**Issue by marcandrebrochu** [Shirakumo/radiance#63]
Thanks for the software! Sadly I run into a compilation error after the following steps:

I boot into a fresh Void Linux system (using glibc, in a Docker container with image void-glibc:46f5dc6). Of course I install some crucial dependencies like automake, tar and gzip. Please note that I got this error while trying to install Radiance on my desktop; here I'm just using a Docker container to minimize free parameters in order to be certain that it is a problem with Radiance and not with my environment.

First I install Roswell 22.12.14.113 using my package manager (xbps):
```bash
$ ros version
roswell 22.12.14.113(NO-GIT-REVISION)
build with cc (GCC) 12.2.0
libcurl=7.87.0
Quicklisp=2021-02-13
Dist=2023-10-21
lispdir='/etc/roswell/'
homedir='/root/.roswell/'
configdir='/root/.roswell/'
sbcl-bin-variant=''

$ ros run -- --version
SBCL 2.4.8
```

Then I enter the SBCL REPL using `ros run` and I try to install Radiance. However the installation steps from the Radiance homepage fail to complete due to the following compilation error:
```
; caught ERROR:
;   READ error during COMPILE-FILE:
;   
;     Package DATABASE does not exist.
;   
;       Line: 45, Column: 108, File-Position: 1743
;   
;       Stream: #<SB-INT:FORM-TRACKING-STREAM for "file /root/.roswell/lisp/quicklisp/dists/shirakumo/software/radiance-2f24a7b13ab9ce723055fa72159bfffb59f4db4a/standard-interfaces.lisp"
```
See attached [SBCL session](https://github.com/user-attachments/files/17183131/SBCL.Session.txt).

This failure is due to the latest commit 2f24a7b, because if I undo that commit (by manually going into the file `standard-interfaces.lisp` downloaded by Quicklisp, and undoing by hand the changes listed in the commit), then the Radiance system is correctly compiled and loaded after going back into the REPL and entering `(ql:quickload :radiance)`.

As I am a Lisp beginner, I'm unsure what are the significance of the changes brought by the previously mentioned commit. Please advise so that I can make a pull request, otherwise please fix it. Thanks!

**Comment by Shinmera** [comment]
Sorry about that. The bug has been fixed and the dist updated to the latest.
